import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.className}`}>
      <body className={geistMono.className}>
        <div className="min-h-screen flex flex-col">
          <Navbar />

          <main className="mx-auto w-full max-w-6xl flex-1 px-6 py-10 animate-rise">
            {children}
          </main>

          <Footer />
        </div>
      </body>
    </html>
  );
}
